import java.util.HashMap;
import java.util.Map;

public class LiteratureTheatreFilm {

	public static Map LiteratureTheatreFilmMap() {
		Map<String, String> map = new HashMap();
		map.put("Action adventure", "Пригодницький екшн");
		map.put("Action", "Екшн");
		map.put("Adaption", "Адаптація, переробка");
		map.put("Animation", "Анімація");
		map.put("Audience", "Аудиторія (слухачі)");
		map.put("Bestseller", "Бестселер");
		map.put("Blockbuster", "Блокбастер");
		map.put("Box office", "Театральна каса");
		map.put("Cartoon", "Мультфільм");
		map.put("Cast", "Група акторів");
		map.put("Character", "Персонаж, герой");
		map.put("Cinema", "Кінотеатр");
		map.put("Climax", "Кульмінація");
		map.put("Comedy", "Комедія");
		map.put("Conflict", "Конфлікт");
		map.put("Credits", "Репутація, пошана");
		map.put("Critic", "Критика");
		map.put("Detective story", "Детектив");
		map.put("Director", "Режисер");
		map.put("Direct", "Режисерувати");
		map.put("Disaster movie", "Фільм-катастрофа");
		map.put("Documentary", "Документальний фільм");
		map.put("Drama", "Драма");
		map.put("Dub", "Дублювати");
		map.put("Dubbing", "Дубляж");
		map.put("Feature film", "Художній фільм");
		map.put("Fiction", "Фантастика");
		map.put("Film", "Фільм");
		map.put("Based on", "Оснований на");
		map.put("Flop", "Зазнати невдачі");
		map.put("Horror", "Жахи");
		map.put("Interval", "Антракт");
		map.put("Leading role", "Провідна роль, головна роль");
		map.put("Literary", "Літературний");
		map.put("Literary criticism", "Літературна критика");
		map.put("Love story", "Любовна історія");
		map.put("Non-fiction", "Художня література");
		map.put("Novel", "Роман");
		map.put("Novelist", "Романіст");
		map.put("Performer", "Той що виступає");
		map.put("Performance", "Виступ");
		map.put("Play", "П’єса");
		map.put("Playwright", "Драматург");
		map.put("Plot", "Сюжет");
		map.put("Poem", "Вірш");
		map.put("Poet", "Поет");
		map.put("Poetry", "Поезія");
		map.put("Prequel", "Передісторія");
		map.put("Protagonist", "Протагоніст");
		map.put("Resolution", "Розв’язка");
		map.put("Review", "Огляд");
		map.put("Reviewer", "Рецензент");
		map.put("Romantic comedy", "Романтична комедія");
		map.put("Scene", "Сцена");
		map.put("Sci-fi (science fiction)", "Наукова фантастика");
		map.put("Screenplay", "Сценарій");
		map.put("Sequel to sth", "Сіквел");
		map.put("Set", "Відбуватися");
		map.put("To be set", "Відбуватися");
		map.put("To go to the cinema", "Ходити в кіно");
		map.put("Row", "Ряд");
		map.put("Short story", "Оповідання");
		map.put("Show", "Шоу");
		map.put("Sound track", "Саундтрек");
		map.put("Special effects", "Спецефекти");
		map.put("Spectator", "Глядач");
		map.put("Stage", "Сцена");
		map.put("Star", "Зірка");
		map.put("Stuntman", "Каскадер");
		map.put("Subtitles", "Субтитри");
		map.put("Supporting (role)", "Другорядна роль");
		map.put("Theme", "Тема");
		map.put("Thriller", "Триллер");
		map.put("Trailer", "Трейлер");
		map.put("Western", "Вестерн");
		return map;
	}
}
