import java.util.HashMap;
import java.util.Map;

public class MusicAndDance {

	public static Map musicAndDanceMap() {
		Map<String, String> map = new HashMap();
		map.put("Album", "Альбом");
		map.put("Backing singers", "Бек вокал");
		map.put("Ballet", "Балет");
		map.put("Band", "Гурт");
		map.put("Bassoon", "Фагот");
		map.put("Beat", "Удар");
		map.put("Blues", "Блюз");
		map.put("Brass", "Духові (з латуні)");
		map.put("CD", "Диск");
		map.put("Cello (pl. cellos)", "Віолончель");
		map.put("Charts", "Чарти");
		map.put("Choir", "Хор");
		map.put("Choreography", "Хореографія");
		map.put("Chorus", "Приспів");
		map.put("Clarinet", "Кларнет");
		map.put("Classical", "Класика");
		map.put("Compose (composer)", "Компонувати (композитор)");
		map.put("Concert", "Концерт");
		map.put("Concert hall", "Концертний зал");
		map.put("Conduct", "Диригувати");
		map.put("Conductor", "Диригент");
		map.put("Contemporary", "Контемпорарі (сучасний)");
		map.put("Country", "Кантрі");
		map.put("Cover version", "Кавер версія (переробка)");
		map.put("Dance", "Танцювати (танець)");
		map.put("Double-bass", "Контрабас");
		map.put("Drum", "Барабан");
		map.put("Flute", "Флейта");
		map.put("Folk", "Фольк");
		map.put("French horn", "Валторна");
		map.put("Gig", "Давати концерт");
		map.put("Group", "Група");
		map.put("Harp", "Арфа");
		map.put("Heavy metal", "Тяжкий метал");
		map.put("Hit", "Хіт");
		map.put("House", "Хауз");
		map.put("Jazz", "Джаз");
		map.put("Lyrics", "Текст пісні");
		map.put("Musical", "Мюзикл");
		map.put("Oboe", "Гобой");
		map.put("Opera", "Опера");
		map.put("Orchestra", "Оркестр");
		map.put("Percussion", "Ударні");
		map.put("Piece", "Твір");
		map.put("Pop", "Поп");
		map.put("R&B", "Реп-енд-блюз");
		map.put("Rap", "Реп");
		map.put("Record", "Записс");
		map.put("Reggae", "Реггі");
		map.put("Release", "Випускати");
		map.put("Rhythm", "Ритм");
		map.put("Rock", "Рок");
		map.put("Rock and pop", "Рок і поп");
		map.put("Singer", "Співак");
		map.put("Sing", "Співати");
		map.put("Single", "Сингл");
		map.put("Solo", "Соло");
		map.put("Song writer", "Автор пісні");
		map.put("String", "Струна");
		map.put("Techno", "Техно");
		map.put("Timpani", "Литавра");
		map.put("Track", "Трек");
		map.put("Triangle", "Трикутник");
		map.put("Trombone", "Тромбон");
		map.put("Trumpet", "Труба");
		map.put("Tuba", "Туба");
		map.put("Tune", "Мелодія");
		map.put("Venues", "Місце проведення");
		map.put("Verse", "Куплет");
		map.put("Viola", "Альт");
		map.put("Violin", "Скрипка");
		map.put("Voice", "Голос");
		map.put("Woodwind", "Духові (з дерева)");
		map.put("World music", "Світова музика");
		return map;
	}
}
